### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by kesshei** [kklldog/AgileConfig_Client#11]
1. 客户端连接时，节点状态一直是离线。
2. 客户端列表，选择节点后，不显示正在连接的客户端。

**Comment by kklldog** [comment]
你可能没连上，请仔细看 [常见问题](https://github.com/dotnetcore/AgileConfig/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%EF%BC%8C%E5%BF%85%E7%9C%8B%EF%BC%81%EF%BC%81%EF%BC%81)

**Comment by kklldog** [comment]
client v1.2 有bug  更新最新的。
