### ISSUE TITLE
这个Env参数是用来起什么作用的。

### ISSUE THREAD

**Issue by qcjxberin** [kklldog/AgileConfig_Client#12]
这个Env参数是用来起什么作用的。

**Comment by kklldog** [comment]
env 参数是最新版本1.5 使用的，目前还没release ，1.5之前的填不填都无所谓。

**Comment by kklldog** [comment]
client v1.2 有问题，更新最新的。

**Comment by qcjxberin** [comment]
好的，目前1.2和1.21的方法都是要传env参数吗？

**Comment by kklldog** [comment]
要那个1.21的 1.2的不要用。如果你的服务端是最新的也就是1.5以上的env就是表示client获取哪个环境。不填默认DEV环境。
