### ISSUE TITLE
add net6 targetframework

### ISSUE THREAD

**Issue by EzrealJ** [kklldog/AgileConfig_Client#16]
当环境为net6时；WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete
能否提供多目标编译？

**Comment by kklldog** [comment]
你是要直接集成源代码吗？其实webrequest在当前的场景下问题不大，有空我改成httpclient吧。

**Comment by EzrealJ** [comment]
我还是用nuegt包，只是在源码里发现了这些代码，谢谢

**Comment by kklldog** [comment]
> 我还是用nuegt包，只是在源码里发现了这些代码，谢谢

嗯嗯，这个场景下webrequest不会有大问题的，我自己net6的项目生产好久了。
