### ISSUE TITLE
客户端没有提供websocket正常关闭的方式

### ISSUE THREAD

**Issue by hanlinking** [kklldog/AgileConfig_Client#18]
目前客户端sdk没有提供应用正常关闭时，关闭websocket链接的方式。导致的结果是一旦应用关闭，会导致服务端抛出客户端websoket非正常掉线的异常，建议处理。

**Comment by kklldog** [comment]
这个异常关闭其实没啥问题，反正都是关闭，异常关闭 server 端同样会把这个链接移除掉，并不会影响正常的业务逻辑。
只是我把异常日志打印出来了，看这不太好看吧。
如果加上正常关闭，那么 server 端，反而需要处理 2 种不同的逻辑，client 端也要注入一个 hostservice 来处理 stop app 的逻辑，感觉是把代码给复杂化了。

**Comment by hanlinking** [comment]
> 

客户端有其他方式可以解决这个问题，可以利用AppDomain.CurrentDomain.ProcessExit 事件来处理

**Comment by kklldog** [comment]
修复了，更新最近的 client 及 server 镜像。
