### ISSUE TITLE
serviceRegister.serviceId和serviceRegister.ip port的问题

### ISSUE THREAD

**Issue by yangbocheng** [kklldog/AgileConfig_Client#29]
hi 作者大大
serviceId能否为什么是要必填，空的时候能否随机赋值个guid

serviceRegister.ip port 中ip 和port为空的时候会发生什么哈。

ip，port 无设置时能否自动按 命令行》应用配置》环境变量配置 优先级猜测ip和port，这种情况下分析出的ip如果是*，+时自动获取第一个ipv4或者ipv6地址

**Comment by kklldog** [comment]
https://github.com/dotnetcore/AgileConfig/issues/118
