### ISSUE TITLE
在加入服务注册的配置后,会由于没有缓存目录抛出异常[nuget上的1.6.13版本]

### ISSUE THREAD

**Issue by xushenchen** [kklldog/AgileConfig_Client#31]
如题，我自定义了一个全新缓存目录，当时加上服务注册配置后由于没有找到这个目录抛出异常，这算是BUG还是出于什么原因这么设计？

**Comment by kklldog** [comment]
没有目录应该会创建。检查一下path是否正确，是否创建文件夹的权限。

**Comment by xushenchen** [comment]
> 没有目录应该创建。检查一下路径是否正确，是否创建文件夹的权限。

错误是FromConfiguration中的WriteIdToLocal(cacheDir, appId, serviceId)抛出来的，这里并没有检查生成的缓存文件夹

**Comment by kklldog** [comment]
都定位到了，要不你改一下PR上来，得了。
