### ISSUE TITLE
配置中心配置变更时，注入的IConfiguration数据未发生变更。是设计如此嘛？

### ISSUE THREAD

**Issue by Shaun-Yang** [kklldog/AgileConfig_Client#38]
![image](https://github.com/kklldog/AgileConfig_Client/assets/32256761/0f10d223-a0ef-420b-a16c-bf0413217c49)
可以在 AgileConfigProvider 中用新值覆盖

**Comment by kklldog** [comment]
感谢，上一个版本引入了这个bug，已修复 v-1.6.19
