### ISSUE TITLE
client try to load all the configs but failed

### ISSUE THREAD

**Issue by hellosnowy** [kklldog/AgileConfig_Client#39]
客户端提示System.Net.WebException: 由于目标计算机积极拒绝，无法连接。 [::ffff:192.168.1.100]:5001 (192.168.1.100:5001)

服务端用的docker部署，开放了5000和5001(文档没说要开)端口，镜像版本 kklldog/agile_config:v-1.6.20
客户端框架.net 6, AgileConfig.Client采用nuget包管理，版本1.6.19

疑问，
为什么会连5001端口且报错

**Comment by hellosnowy** [comment]
在服务端的UI  节点或客户端 页面上点击 刷新配置 按钮，客户端就会报上述错错误

**Comment by kklldog** [comment]
需要更多信息来判断。
client 报错的截图，服务端客户端界面的截图，服务端节点界面的截图，服务端docker部署的脚本，客户端配置等信息。。。
