### ISSUE TITLE
为什么示例项目里面啥都没有？

### ISSUE THREAD

**Issue by robyle** [kklldog/AgileConfig_Client#40]
https://github.com/kklldog/AgileConfig_Client/blame/6f9bedc1437ebe75dfdd75eab72616d12dca87f4/AgileConfigWPFSample/MainWindow.xaml.cs#L30-L31

**Comment by kklldog** [comment]
https://github.com/kklldog/AgileConfig_Client/blob/master/AgileConfigWPFSample/App.xaml.cs

**Comment by robyle** [comment]
> https://github.com/kklldog/AgileConfig_Client/blob/master/AgileConfigWPFSample/App.xaml.cs

好的，不过只见初始化，并没有进行变更通知的绑定处理。整个示例略显简单哈~！
