### ISSUE TITLE
IConfiguration中的数据更新慢于ConfigClient.ReLoaded事件

### ISSUE THREAD

**Issue by tomyangOK** [kklldog/AgileConfig_Client#41]
ConfigurationBuilderExtension.AddAgileConfig系列方法中Action[ConfigReloadedArgs]的注册早于AgileConfigProvider中的ReLoaded事件注册，导致配置变更后先触发用户自定义绑定的Action[ConfigReloadedArgs]，而系统级的AgileConfigProvider中绑定的ReLoaded事件执行较晚。进而用户自定义绑定的Action[ConfigReloadedArgs]中无法通过IConfiguration方式获取到最新的配置。

![image](https://github.com/kklldog/AgileConfig_Client/assets/29696604/b28cb8ae-03e2-4389-8c39-805b64b519db)

**Comment by kklldog** [comment]
当然可以，要不你PR?
其实如果是习惯使用 IConfiguration 的话建议还是使用微软原生的 ChangeToken 来监听 IConfiguration 的变化。

**Comment by kklldog** [comment]
感觉 PR，已经 merge 。
RELEASE VERSION: 1.7.0
